# Generated by Django 6.0.1 on 2026-02-02 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0003_category_film_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='update_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
