# Generated by Django 6.0.1 on 2026-02-06 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0004_film_update_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
