# Generated by Django 6.0.1 on 2026-02-09 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0007_genre_film_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='year',
            field=models.PositiveIntegerField(null=True, verbose_name='Год выпуска'),
        ),
    ]
